### ISSUE TITLE
Port from environment

### ISSUE THREAD

**Issue by giuliohome** [geshan/nodejs-sqlite#5]
Please fix [this line](https://github.com/geshan/nodejs-sqlite/blob/master/index.js#L3) `const port = 3000 || process.env.PORT;`

It's obviously

```javascript
const port =  process.env.PORT || 3000;
```

Thanks

**Comment by geshan** [comment]
Hello @giuliohome , thanks for the suggestion. Would you like to open a small PR for that, thanks!

**Comment by giuliohome** [comment]
Sure. As you prefer, will do soon
